# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: use-generate-txt

on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        required: true

jobs:
  generate-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Check Contexts, Inputs, and Secrets
        run: |
          echo "[Contexts]"
          echo "github.job = ${{ github.job }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.number = ${{ github.event.number }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "[Inputs]"
          echo "inputs.VERSION = ${{ inputs.VERSION }}"
          echo "[Secrets]"
          echo "secrets.GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Generate ${{ inputs.VERSION }}.txt
        id: gsi
        shell: bash
        run: |
          mkdir -p $(pwd)/generate
          VERSION_TXT_PATH=$(pwd)/generate/${{ inputs.VERSION }}.txt
          echo $RANDOM > $VERSION_TXT_PATH

      # Sleep 0, 10, 20,..., 40 seconds randomly
      - name: Sleep for random seconds
        shell: bash
        run: |
          SLEEP_TIME=$((RANDOM % 10 * 10))
          sleep ${SLEEP_TIME}s
          echo "sleep ${SLEEP_TIME}s"

      - name: Add and Commit the Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          author_name: docs-l10n[bot]
          author_email: 157310748+docs-l10n[bot]@users.noreply.github.com
          # fetch: false
          pull: '--rebase --autostash'
          # pull: '--rebase --autostash --no-recurse-submodules'
          # pull: '--rebase --autostash --recurse-submodules'
          message: |
            chore(${{ inputs.VERSION }}): Generate Text
